ARG PYTHON_VERSION=3.12
FROM python:${PYTHON_VERSION}-slim

COPY app/requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY app/app.py /root/app.py

# These values will be overidden by CI/CD process
ENV DB_USER="user" \
    DB_PASSWORD="password" \
    DB_HOST="localhost" \
    DB_NAME="counter_db" \
    FLASK_PORT="80"

EXPOSE 80

WORKDIR /root

CMD ["python", "app.py"]
